# Test playbook
---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: users
    - role: repo
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      openio_gridinit_per_ns: true
    - role: namespace
      openio_namespace_name: "{{ NS }}"
    - role: role_under_test
      openio_blob_rebuilder_namespace: "{{ NS }}"
      openio_blob_rebuilder_allow_same_raw: true
      openio_blob_rebuilder_worker: 1
      openio_blob_rebuilder_chunks_per_second: 1
...
